name: init-vcaml-bleeding-project
# TODO: on: push
on: workflow_dispatch
jobs:
  init-vcaml-bleeding-project:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        nvim-version: [v0.9.5, nightly]
        include:
          - os: macos-latest
            tarball: nvim-macos.tar.gz
            install-opam: brew install opam
          - os: ubuntu-latest
            tarball: nvim-linux64.tar.gz
            install-opam: sudo apt-get install opam -y
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install opam
      run: "${{matrix.install-opam}}"
    - name: Download and extract Neovim tarball
      run: |
        curl -LO "https://github.com/neovim/neovim/releases/download/${{matrix.nvim-version}}/${{matrix.tarball}}"
        mkdir -p "${{runner.temp}}/nvim"
        tar -xzvf "${{matrix.tarball}}" -C "${{runner.temp}}/nvim" --strip-components 1
    - name: Initialize vcaml project
      run: |
        chmod +x init-bleeding-vcaml-project.sh
        ./init-bleeding-vcaml-project.sh hello-vcaml
        cd hello-vcaml
        eval "$(opam env)"
        export PATH="${{runner.temp}}/nvim/bin:$PATH"
        dune runtest
