name: init-vcaml-bleeding-project
# TODO: on: push
on: workflow_dispatch
defaults:
  run:
    shell: bash
jobs:
  init-vcaml-bleeding-project:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        ocaml-compiler: ["5.1"]
    runs-on: ${{ matrix.os }}
    env:
      NEOVIM_VERSION: v0.9.5
      NEOVIM_DOWNLOAD_URL: https://github.com/neovim/neovim/releases/download
    steps:
    - name: Download Neovim for Linux
      if: matrix.os == 'ubuntu-latest'
      run: echo "NEOVIM_TARBALL=nvim-linux64.tar.gz" >> "$GITHUB_ENV"
    - name: Download Neovim for MacOS
      if: matrix.os == 'macos-latest'
      run: echo "NEOVIM_TARBALL=nvim-macos.tar.gz" >> "$GITHUB_ENV"
    - name: Download Neovim and add it to PATH
      run: |
        echo "$NEOVIM_DOWNLOAD_URL"
        echo "$NEOVIM_VERSION"
        echo "$NEOVIM_TARBALL"
        curl -L "$NEOVIM_DOWNLOAD_URL/$NEOVIM_VERSION/$NEOVIM_TARBALL" -o nvim.tar.gz
        mkdir nvim
        tar -xzvf nvim.tar.gz -C nvim --strip-components 1
        echo "PATH=$PWD/nvim/bin:$PATH" >> "$GITHUB_ENV"
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Install opam
      uses: ocaml/setup-ocaml@v2
      with:
        ocaml-compiler: ${{ matrix.ocaml-compiler }}
    - name: Initialize vcaml project
      run: |
        chmod +x init-bleeding-vcaml-project.sh
        ./init-bleeding-vcaml-project.sh hello-vcaml
        cd hello-vcaml
        eval "$(opam env)"
        dune runtest
