name: scratch
on: workflow_dispatch
defaults:
  run:
    shell: bash
jobs:
  init-vcaml-bleeding-project:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Download Opam for Linux
      if: matrix.os == 'ubuntu-latest'
      run: apt-get install opam -y
    - name: Download Opam for MacOS
      if: matrix.os == 'macos-latest'
      run: brew install opam
