
name: scratch
# TODO: on: push
on: workflow_dispatch
jobs:
  init-vcaml-bleeding-project:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    env:
      NEOVIM_VERSION: v0.9.5
      NEOVIM_DOWNLOAD_URL: https://github.com/neovim/neovim/releases/download
    steps:
    - name: Choose Neovim tarball for MacOS
      run: echo "NEOVIM_TARBALL=nvim-macos.tar.gz" >> "$GITHUB_ENV"
    - name: Download and extract Neovim tarball; add nvim to PATH
      run: |
        echo "$NEOVIM_DOWNLOAD_URL"
        echo "$NEOVIM_VERSION"
        echo "$NEOVIM_TARBALL"
        curl -L "$NEOVIM_DOWNLOAD_URL/$NEOVIM_VERSION/$NEOVIM_TARBALL" -o nvim.tar.gz
        mkdir nvim
        tar -xzvf nvim.tar.gz -C nvim --strip-components 1
        echo "PATH=$PWD/nvim/bin:$PATH" >> "$GITHUB_ENV"
    - name: Sanity checks
      run: |
        echo "Path: $PATH"
        echo "Which nvim? $(which nvim)"
