
name: scratch
# TODO: on: push
on: workflow_dispatch
jobs:
  init-vcaml-bleeding-project:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Sanity checks
      run: |
        echo "Pwd: $PWD"
        echo "Home: $HOME"
